AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'bin/*'
    - 'test/**/*'
    - 'config.ru'
    - 'app/helpers/**/*'
    - 'app/mailers/**/*'
    - 'app/jobs/**/*' 

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30